<a href="https://colab.research.google.com/github/sj-py/deeplearning/blob/master/codingapple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

텐서 = tf.constant([3,4,5])#정수 및 여러 숫자(데이터), 리스트형태도 가능
텐서2 = tf.constant([6,7,8])

텐서3 = tf.constant([[1,2], 
                    [3,4]])
텐서4 = tf.constant([[5,6],
                    [7,8]])

print(tf.add(텐서, 텐서2))#+
print(tf.subtract(텐서, 텐서2))#-
print(tf.divide(텐서, 텐서2))#/
print(tf.multiply(텐서, 텐서2))#*
print(tf.matmul(텐서3, 텐서4))#행렬의 곱 반드시 행렬끼리만 실행

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)
tf.Tensor([18 28 40], shape=(3,), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
